apiVersion: v1
kind: Secret
metadata:
  name: rag-credentials
  namespace: tbb
type: Opaque
stringData:
  # IBM Watsonx Credentials
  watsonx-api-key: "key_here"
  watsonx-project-id: "14431c61-b5a8-4d06-81e4-a3b55bbea942"
  
  # Milvus Credentials
  milvus-password: "Milvus"
